const express = require('express');
const router = express.Router();
const STATUS = require('http-status-codes');
const multer = require('multer');
var upload = multer({ dest: 'uploads/' }); //setting the default 
const { Photo } = require('./../models');
var fs = require('fs');

router.get('/', async (req, res) => { // List
    const photos = await Photo.findAll();
    res.status(STATUS.OK).json({msg: 'Found all photos', photos});
});


router.post('/upload', upload.single('fileData'), (req, res,next) => {
    //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
    fs.readFile(req.file.path, (err, contents)=> {
     if (err) {
     console.log('Error: ', err);
    }else{
     console.log('File contents ',contents);
    }
   });
  });

router.post('/object', (req, res) => { // Create
    res.send("OK COMPUTER - Work in progress...")
});

router.get('/:id', async (req, res) => { // Search
    const photo = Photo.findOne({where: {id: req.params.id}});

    if (photo)
    {
        res.status(STATUS.OK).json({msg: 'Found photo', photo});
    } 
    else 
    {
        res.status(STATUS.INTERNAL_SERVER_ERROR).json({msg: 'No photo was found'});
    }
});


router.patch('/:id', (req, res) => { // Edit
    
});


router.delete('/:id', (req, res) => { // Delete
    const deleted = Photo.destroy({where: {id: req.params.id}});

    if (deleted) 
    {
        res.status(STATUS.OK).json({msg: 'Photo was deleted'});
    } else {
        res.status(STATUS.INTERNAL_SERVER_ERROR).json({msg: 'Something went wrong when deleting the photo'});
    }
});


module.exports = router;